"""app/routers/anomaly.py — Anomaly detection endpoints."""

from fastapi import APIRouter, Depends, Query, status
from sqlalchemy import or_
from sqlalchemy.orm import Session

from app.database import get_db
from app.dependencies import get_current_user
from app.models import Anomaly, MarketData, User
from app.schemas import AnomalyDetectRequest, AnomalyPaginatedResponse, AnomalyResponse
from app.services.anomaly_service import detect_anomaly

router = APIRouter(prefix="/anomalies", tags=["anomalies"])


@router.get("", response_model=AnomalyPaginatedResponse)
def list_anomalies(
    limit: int = Query(20, ge=1, le=100),
    offset: int = Query(0, ge=0),
    symbol: str | None = Query(None, description="Filter by symbol"),
    is_anomaly: bool | None = Query(None, description="Filter by anomaly status"),
    primary_signal: str | None = Query(None, description="Filter by primary signal"),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    List anomalies.
    Returns anomalies owned by the current user OR generated by the system user.
    """
    system_user = db.query(User).filter(
        or_(
            User.email == "system@marketsurveillance.local",
            User.email == "system_surveillance@example.com"
        )
    ).first()
    system_user_id = system_user.id if system_user else None

    query = db.query(Anomaly, MarketData).join(MarketData, Anomaly.market_data_id == MarketData.id)
    query = query.filter(
        or_(
            MarketData.user_id == current_user.id,
            MarketData.user_id == system_user_id
        )
    )

    if symbol:
        query = query.filter(MarketData.symbol == symbol.upper())
    
    if is_anomaly is not None:
        query = query.filter(Anomaly.is_anomaly == is_anomaly)
        
    if primary_signal:
        query = query.filter(Anomaly.primary_signal == primary_signal)
        
    total = query.count()
    results = query.order_by(Anomaly.detected_at.desc(), Anomaly.id.desc()).offset(offset).limit(limit).all()
    
    items = []
    for anomaly, md in results:
        item_dict = anomaly.__dict__.copy()
        item_dict["symbol"] = md.symbol
        item_dict["market_timestamp"] = md.timestamp
        item_dict["market"] = md.market
        item_dict["severity"] = anomaly.severity

        # --- Inject explainability fields from stored raw features ---
        # The live stream path always computes these at scoring time.
        # For historical records we reconstruct them from the stored features
        # JSON so the frontend can render the same evidence panel.
        item_dict["evidence"] = None
        item_dict["detection_result"] = None
        item_dict["detector_agreement"] = None
        item_dict["weak_label_confidence"] = None

        try:
            import json
            import logging

            from ml.explainability import generate_evidence_signals

            from app.schemas import DetectionResultSchema, EvidenceSignalSchema

            raw_features = json.loads(anomaly.features) if anomaly.features else {}
            pattern_scores = json.loads(anomaly.pattern_scores) if anomaly.pattern_scores else {}

            raw_dicts = generate_evidence_signals(
                raw_features, 
                anomaly.isolation_forest_score, 
                anomaly.multi_pattern_max_score
            )
            evidence_signals = [EvidenceSignalSchema(**sig) for sig in raw_dicts]

            from app.models import check_detector_agreement
            da = check_detector_agreement(anomaly.isolation_forest_score, anomaly.multi_pattern_max_score)
            if da == 1.0:
                evidence_signals.append(EvidenceSignalSchema(name="dual_detector_agreement", value=1.0, threshold=1.0, triggered=True))

            # weak_label_confidence from pattern score distribution
            wlc = None
            if pattern_scores and len(pattern_scores) > 1:
                scores_arr = sorted(pattern_scores.values(), reverse=True)
                wlc = round(scores_arr[0] / (scores_arr[0] + scores_arr[1] + 1e-9), 4)
                if da is not None:
                    wlc = round(wlc * da, 4)
            elif pattern_scores:
                wlc = round(list(pattern_scores.values())[0], 4)

            best_pattern = max(pattern_scores, key=pattern_scores.get) if pattern_scores else None

            item_dict["evidence"] = evidence_signals if evidence_signals else None
            item_dict["detector_agreement"] = da
            item_dict["weak_label_confidence"] = wlc

            if evidence_signals or best_pattern:
                item_dict["detection_result"] = DetectionResultSchema(
                    label=best_pattern or "anomaly",
                    confidence=wlc or 0.0,
                    detector_score=anomaly.anomaly_score,
                    detector_agreement=da or 0.0,
                    source="stored",
                    evidence=evidence_signals,
                )
        except Exception as e:
            # Log the failure but don't break the list endpoint
            logging.error("Failed to generate explainability for anomaly %s: %s", anomaly.id, e, exc_info=True)
        items.append(item_dict)
        
    return AnomalyPaginatedResponse(
        items=items,
        total=total,
        limit=limit,
        offset=offset
    )


@router.post("", response_model=AnomalyResponse, status_code=status.HTTP_201_CREATED)
def run_anomaly_detection(
    payload: AnomalyDetectRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Run anomaly detection on an existing market data record.
    Returns the anomaly result including the composite score.
    """
    return detect_anomaly(
        db=db,
        market_data_id=payload.market_data_id,
        user_id=current_user.id,
        threshold=payload.threshold,
    )


@router.get("/models/status")
def get_model_status(
    current_user: User = Depends(get_current_user),
):
    """Return runtime model telemetry and active detectors for authenticated analysts."""
    from app.services.anomaly_service import get_models_health_status
    return get_models_health_status()
